import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RoleProvider } from "@/providers/RoleProvider";
import AuthProvider from "@/services/next-auth/components/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans leading-[1.2]`}
      >
        <AuthProvider>
          <Suspense>
            <RoleProvider>{children}</RoleProvider>
          </Suspense>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
